Homework 1
beaufsichtigen/IuliiaKulagina pull request #2
Opened 2022-12-08 11:16 UTC by beaufsichtigen

2022-12-11 18:45 UTC, obitkin requested changes
There are only very simple tests. No one is failing. Expected exceptions haven't been used. But you almost match requirements. Change java version and remove java version duplication. So, it will be approved

2022-12-11 18:45 UTC, obitkin commented on pom.xml
> +        <maven.compiler.target>18</maven.compiler.target>
Change to version 11

2022-12-11 21:11 UTC, beaufsichtigen commented on pom.xml
> +        <maven.compiler.target>18</maven.compiler.target>
Fixed

2022-12-14 13:32 UTC, obitkin requested changes

2022-12-14 14:13 UTC, beaufsichtigen commented on pom.xml
> +    </build>
Corrected. After fixes, a bug was found that static imports in classes should be one line higher. Fixed as well.

2022-12-14 14:15 UTC, beaufsichtigen commented on src/test/java/com/epam/tc/hw1/AbstractTest.java
> +//        }
I left it because it would be more convenient for me to use it as a template.
Deleted with a new commit.

2022-12-15 12:22 UTC, obitkin approved these changes
Approved

2022-12-15 13:26 UTC, merged